use super::*;

pub(super) const MALE_RUNTIME_CLIPS: [(&str, i64, &str); 113] = [
    ("stand1", 237_023, "male-stand1.json"),
    ("height_Add", 34_244, "male-height-add.json"),
    ("height", 34_245, "male-height.json"),
    ("shape_Add", 34_248, "male-shape-add.json"),
    ("shape", 34_253, "male-shape.json"),
    ("riflestand1", 34_381, "male-riflestand1.json"),
    ("stickstand1", 34_393, "male-stickstand1.json"),
    ("pistolstand1", 34_299, "male-pistolstand1.json"),
    ("run", 34_268, "male-run.json"),
    ("staying", 34_269, "male-staying.json"),
    ("standup", 34_404, "male-standup.json"),
    ("runback", 34_249, "male-runback.json"),
    ("jumpstart", 34_390, "male-jumpstart.json"),
    ("jump", 34_314, "male-jump.json"),
    ("jumpend", 34_224, "male-jumpend.json"),
    ("jumplandrun", 34_256, "male-jumplandrun.json"),
    // Primary CharacterSelection.resourceFile actor/m.kfm preload; exact
    // AnimationClip objects used by cnAvatarAnimation.AvatarDead/EndAnimation.
    ("die", 34_531, "male-die.json"),
    ("death", 34_462, "male-death.json"),
    ("rifleready", 34_367, "male-rifleready.json"),
    ("stickattack1", 34_332, "male-stickattack1.json"),
    ("stickattack1upper", 34_412, "male-stickattack1upper.json"),
    ("pistolattack1", 34_380, "male-pistolattack1.json"),
    ("pistolattack1upper", 34_240, "male-pistolattack1upper.json"),
    ("rifleattack1", 34_555, "male-rifleattack1.json"),
    ("rifleattack1upper", 34_305, "male-rifleattack1upper.json"),
    ("riflerun", 34_321, "male-riflerun.json"),
    ("riflerunback", 34_331, "male-riflerunback.json"),
    ("riflejumpstart", 34_354, "male-riflejumpstart.json"),
    ("riflejump", 34_387, "male-riflejump.json"),
    ("riflejumpend", 34_415, "male-riflejumpend.json"),
    ("riflejumplandrun", 34_365, "male-riflejumplandrun.json"),
    ("turnleft", 34_346, "male-turnleft.json"),
    ("turnright", 34_384, "male-turnright.json"),
    ("rifleturnleft", 34_231, "male-rifleturnleft.json"),
    ("rifleturnright", 34_216, "male-rifleturnright.json"),
    ("swim", 34_486, "male-swim.json"),
    ("swimback", 34_453, "male-swimback.json"),
    ("swimidle", 34_524, "male-swimidle.json"),
    ("swimleft", 34_535, "male-swimleft.json"),
    ("swimright", 34_514, "male-swimright.json"),
    ("stickready", 34_220, "male-stickready.json"),
    ("stickrun", 34_208, "male-stickrun.json"),
    ("stickrunback", 34_252, "male-stickrunback.json"),
    ("stickjumpstart", 34_233, "male-stickjumpstart.json"),
    ("stickjump", 34_320, "male-stickjump.json"),
    ("stickjumpend", 34_312, "male-stickjumpend.json"),
    ("stickjumplandrun", 34_300, "male-stickjumplandrun.json"),
    ("pistolready", 34_255, "male-pistolready.json"),
    ("pistolrun", 34_374, "male-pistolrun.json"),
    ("pistolrunback", 34_349, "male-pistolrunback.json"),
    ("pistoljumpstart", 34_212, "male-pistoljumpstart.json"),
    ("pistoljump", 34_302, "male-pistoljump.json"),
    ("pistoljumpend", 34_234, "male-pistoljumpend.json"),
    ("pistoljumplandrun", 34_221, "male-pistoljumplandrun.json"),
    ("bombstand1", 34_401, "male-bombstand1.json"),
    ("bombready", 34_226, "male-bombready.json"),
    ("bombattack1", 34_297, "male-bombattack1.json"),
    ("bombattack1upper", 34_436, "male-bombattack1upper.json"),
    ("bombrun", 34_262, "male-bombrun.json"),
    ("bombrunback", 237_032, "male-bombrunback.json"),
    ("bombjumpstart", 34_267, "male-bombjumpstart.json"),
    ("bombjump", 34_560, "male-bombjump.json"),
    ("bombjumpend", 34_599, "male-bombjumpend.json"),
    ("bombjumplandrun", 34_288, "male-bombjumplandrun.json"),
    ("rocketstand1", 34_624, "male-rocketstand1.json"),
    ("rocketready", 34_521, "male-rocketready.json"),
    ("rocketattack1", 34_301, "male-rocketattack1.json"),
    ("rocketattack1upper", 34_210, "male-rocketattack1upper.json"),
    ("rocketrun", 34_534, "male-rocketrun.json"),
    ("rocketrunback", 34_518, "male-rocketrunback.json"),
    ("rocketjumpstart", 34_441, "male-rocketjumpstart.json"),
    ("rocketjump", 34_422, "male-rocketjump.json"),
    ("rocketjumpend", 34_303, "male-rocketjumpend.json"),
    ("rocketjumplandrun", 34_484, "male-rocketjumplandrun.json"),
    // Primary CharacterSelection.resourceFile, actor/m.kfm Animation #234214.
    ("slide", 34_408, "male-slide.json"),
    ("ropedown", 34_214, "male-ropedown.json"),
    ("inven", 34_276, "male-inven.json"),
    ("board_inven", 34_399, "male-board-inven.json"),
    ("scooter_inven", 34_583, "male-scooter-inven.json"),
    ("ropedrop", 34_348, "male-ropedrop.json"),
    ("ropeleft", 34_334, "male-ropeleft.json"),
    ("roperight", 34_350, "male-roperight.json"),
    ("ropestand1", 34_361, "male-ropestand1.json"),
    ("ropestand2", 34_327, "male-ropestand2.json"),
    ("ropeturn", 34_606, "male-ropeturn.json"),
    ("ropeup", 34_335, "male-ropeup.json"),
    // Primary CharacterSelection.resourceFile, actor/m.kfm Animation #234214.
    // These are the no-prefix clips selected while the Hand slot is empty.
    ("attack1", 34_235, "male-attack1.json"),
    ("attack1upper", 34_213, "male-attack1upper.json"),
    // Clean EmoteAnimationTable clips used by AvatarEmote(int), all owned by
    // primary CharacterSelection.resourceFile actor/m.kfm.
    ("cry", 34_471, "male-cry.json"),
    ("angry", 34_304, "male-angry.json"),
    ("shocked", 34_383, "male-shocked.json"),
    ("hello", 34_598, "male-hello.json"),
    ("thank", 34_362, "male-thank.json"),
    ("dance1", 34_566, "male-dance1.json"),
    ("kiss", 34_427, "male-kiss.json"),
    ("agree", 34_319, "male-agree.json"),
    ("laugh", 34_353, "male-laugh.json"),
    ("no", 34_410, "male-no.json"),
    ("flex", 34_558, "male-flex.json"),
    ("tease", 34_623, "male-tease.json"),
    ("ok", 34_423, "male-ok.json"),
    ("applaud", 34_217, "male-applaud.json"),
    ("cheer", 34_405, "male-cheer.json"),
    ("dance2", 34_285, "male-dance2.json"),
    ("dance3", 34_225, "male-dance3.json"),
    ("dance4", 34_635, "male-dance4.json"),
    ("dance5", 34_316, "male-dance5.json"),
    ("goodbye", 34_310, "male-goodbye.json"),
    ("beach1", 34_211, "male-beach1.json"),
    ("beach2", 34_402, "male-beach2.json"),
    ("beach3", 34_433, "male-beach3.json"),
    // Primary CharacterSelection.resourceFile actor/m.kfm clips selected by
    // cnAvatarAnimation.AvatarBroomStick/EndAnimation.
    ("mount1", 34_330, "male-mount1.json"),
    ("mount2", 34_338, "male-mount2.json"),
];

pub(super) const FEMALE_RUNTIME_CLIPS: [(&str, i64, &str); 113] = [
    ("stand1", 237_027, "female-stand1.json"),
    ("height_Add", 34_516, "female-height-add.json"),
    ("height", 34_475, "female-height.json"),
    ("shape_Add", 34_227, "female-shape-add.json"),
    ("shape", 34_372, "female-shape.json"),
    ("riflestand1", 34_382, "female-riflestand1.json"),
    ("stickstand1", 34_457, "female-stickstand1.json"),
    ("pistolstand1", 34_175, "female-pistolstand1.json"),
    ("run", 34_191, "female-run.json"),
    ("staying", 34_194, "female-staying.json"),
    ("standup", 34_533, "female-standup.json"),
    ("runback", 34_611, "female-runback.json"),
    ("jumpstart", 34_557, "female-jumpstart.json"),
    ("jump", 34_605, "female-jump.json"),
    ("jumpend", 34_626, "female-jumpend.json"),
    ("jumplandrun", 34_567, "female-jumplandrun.json"),
    // Primary CharacterSelection.resourceFile actor/w.kfm preload; exact
    // AnimationClip objects used by cnAvatarAnimation.AvatarDead/EndAnimation.
    ("die", 34_444, "female-die.json"),
    ("death", 34_537, "female-death.json"),
    ("rifleready", 34_595, "female-rifleready.json"),
    ("stickattack1", 34_579, "female-stickattack1.json"),
    ("stickattack1upper", 34_315, "female-stickattack1upper.json"),
    ("pistolattack1", 34_414, "female-pistolattack1.json"),
    (
        "pistolattack1upper",
        34_286,
        "female-pistolattack1upper.json",
    ),
    ("rifleattack1", 34_445, "female-rifleattack1.json"),
    ("rifleattack1upper", 34_466, "female-rifleattack1upper.json"),
    ("riflerun", 34_585, "female-riflerun.json"),
    ("riflerunback", 34_578, "female-riflerunback.json"),
    ("riflejumpstart", 34_603, "female-riflejumpstart.json"),
    ("riflejump", 34_627, "female-riflejump.json"),
    ("riflejumpend", 34_571, "female-riflejumpend.json"),
    ("riflejumplandrun", 34_559, "female-riflejumplandrun.json"),
    ("turnleft", 34_469, "female-turnleft.json"),
    ("turnright", 34_619, "female-turnright.json"),
    ("rifleturnleft", 34_622, "female-rifleturnleft.json"),
    ("rifleturnright", 34_612, "female-rifleturnright.json"),
    ("swim", 34_185, "female-swim.json"),
    ("swimback", 34_165, "female-swimback.json"),
    ("swimidle", 34_512, "female-swimidle.json"),
    ("swimleft", 34_503, "female-swimleft.json"),
    ("swimright", 34_498, "female-swimright.json"),
    ("stickready", 34_155, "female-stickready.json"),
    ("stickrun", 34_198, "female-stickrun.json"),
    ("stickrunback", 34_188, "female-stickrunback.json"),
    ("stickjumpstart", 34_523, "female-stickjumpstart.json"),
    ("stickjump", 34_278, "female-stickjump.json"),
    ("stickjumpend", 34_474, "female-stickjumpend.json"),
    ("stickjumplandrun", 34_451, "female-stickjumplandrun.json"),
    ("pistolready", 34_170, "female-pistolready.json"),
    ("pistolrun", 34_151, "female-pistolrun.json"),
    ("pistolrunback", 34_147, "female-pistolrunback.json"),
    ("pistoljumpstart", 34_143, "female-pistoljumpstart.json"),
    ("pistoljump", 34_527, "female-pistoljump.json"),
    ("pistoljumpend", 34_166, "female-pistoljumpend.json"),
    ("pistoljumplandrun", 34_200, "female-pistoljumplandrun.json"),
    ("bombstand1", 34_593, "female-bombstand1.json"),
    ("bombready", 34_565, "female-bombready.json"),
    ("bombattack1", 34_500, "female-bombattack1.json"),
    ("bombattack1upper", 34_542, "female-bombattack1upper.json"),
    ("bombrun", 34_556, "female-bombrun.json"),
    ("bombrunback", 237_031, "female-bombrunback.json"),
    ("bombjumpstart", 34_630, "female-bombjumpstart.json"),
    ("bombjump", 34_530, "female-bombjump.json"),
    ("bombjumpend", 34_613, "female-bombjumpend.json"),
    ("bombjumplandrun", 34_633, "female-bombjumplandrun.json"),
    ("rocketstand1", 34_546, "female-rocketstand1.json"),
    ("rocketready", 34_511, "female-rocketready.json"),
    ("rocketattack1", 34_452, "female-rocketattack1.json"),
    (
        "rocketattack1upper",
        34_199,
        "female-rocketattack1upper.json",
    ),
    ("rocketrun", 34_502, "female-rocketrun.json"),
    ("rocketrunback", 34_497, "female-rocketrunback.json"),
    ("rocketjumpstart", 34_163, "female-rocketjumpstart.json"),
    ("rocketjump", 34_154, "female-rocketjump.json"),
    ("rocketjumpend", 34_164, "female-rocketjumpend.json"),
    ("rocketjumplandrun", 34_187, "female-rocketjumplandrun.json"),
    // Primary CharacterSelection.resourceFile, actor/w.kfm Animation #234274.
    ("slide", 34_572, "female-slide.json"),
    ("ropedown", 34_618, "female-ropedown.json"),
    ("inven", 34_614, "female-inven.json"),
    ("board_inven", 34_413, "female-board-inven.json"),
    ("scooter_inven", 34_435, "female-scooter-inven.json"),
    ("ropedrop", 34_190, "female-ropedrop.json"),
    ("ropeleft", 34_169, "female-ropeleft.json"),
    ("roperight", 34_162, "female-roperight.json"),
    ("ropestand1", 34_152, "female-ropestand1.json"),
    ("ropestand2", 34_204, "female-ropestand2.json"),
    ("ropeturn", 34_507, "female-ropeturn.json"),
    ("ropeup", 34_193, "female-ropeup.json"),
    // Primary CharacterSelection.resourceFile, actor/w.kfm Animation #234274.
    // These are the no-prefix clips selected while the Hand slot is empty.
    ("attack1", 34_171, "female-attack1.json"),
    ("attack1upper", 34_174, "female-attack1upper.json"),
    // Clean EmoteAnimationTable clips used by AvatarEmote(int), all owned by
    // primary CharacterSelection.resourceFile actor/w.kfm.
    ("cry", 34_494, "female-cry.json"),
    ("angry", 34_161, "female-angry.json"),
    ("shocked", 34_629, "female-shocked.json"),
    ("hello", 34_192, "female-hello.json"),
    ("thank", 34_476, "female-thank.json"),
    ("dance1", 34_283, "female-dance1.json"),
    ("kiss", 34_602, "female-kiss.json"),
    ("agree", 34_201, "female-agree.json"),
    ("laugh", 34_377, "female-laugh.json"),
    ("no", 34_250, "female-no.json"),
    ("flex", 34_218, "female-flex.json"),
    ("tease", 34_547, "female-tease.json"),
    ("ok", 34_431, "female-ok.json"),
    ("applaud", 34_149, "female-applaud.json"),
    ("cheer", 34_515, "female-cheer.json"),
    ("dance2", 34_430, "female-dance2.json"),
    ("dance3", 34_536, "female-dance3.json"),
    ("dance4", 34_634, "female-dance4.json"),
    ("dance5", 34_628, "female-dance5.json"),
    ("goodbye", 34_575, "female-goodbye.json"),
    ("beach1", 34_573, "female-beach1.json"),
    ("beach2", 34_563, "female-beach2.json"),
    ("beach3", 34_552, "female-beach3.json"),
    // Primary CharacterSelection.resourceFile actor/w.kfm clips selected by
    // cnAvatarAnimation.AvatarBroomStick/EndAnimation.
    ("mount1", 34_280, "female-mount1.json"),
    ("mount2", 34_294, "female-mount2.json"),
];

pub(super) const CUSTOM_RUNTIME_CLIPS: [CustomRuntimeClipSpec; 14] = [
    custom_runtime_clip(
        "ffr_dance_02",
        "f_dance_02",
        644,
        "f_dance_02.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_04",
        "f_dance_04",
        624,
        "f_dance_04.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_07",
        "f_dance_07",
        641,
        "f_dance_07.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_08",
        "f_dance_08",
        629,
        "f_dance_08.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_10",
        "f_dance_10",
        607,
        "f_dance_10.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_13",
        "f_dance_13",
        604,
        "f_dance_13.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_15",
        "f_dance_15",
        610,
        "f_dance_15.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_18",
        "f_dance_18",
        646,
        "f_dance_18.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_19",
        "f_dance_19",
        637,
        "f_dance_19.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_dance_20",
        "f_dance_20",
        585,
        "f_dance_20.json",
        102,
        68,
    ),
    CustomRuntimeClipSpec {
        semantic_name: "ffr_dance_bully",
        female_source_name: "f_dance_bully",
        female_source_path_id: 645,
        female_source_file: "f_dance_bully.json",
        male_source_name: "m_dance_bully",
        male_source_path_id: 642,
        male_source_file: "m_dance_bully.json",
        female_minimum_mapped_paths: 102,
        male_minimum_mapped_paths: 132,
    },
    custom_runtime_clip(
        "ffr_dance_tellme",
        "f_dance_tellme",
        648,
        "f_dance_tellme.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_emote_catpose",
        "f_emote_catpose",
        639,
        "f_emote_catpose.json",
        102,
        68,
    ),
    custom_runtime_clip(
        "ffr_emote_idolpose",
        "f_emote_idolpose",
        623,
        "f_emote_idolpose.json",
        102,
        68,
    ),
];
