
/// These are the exact legacy owner groups proven to contain Nano ability audio.
/// Keeping a closed set is intentional: similarly named world/NPC sounds such as
/// `recall_warp` and `vampire_bb_*` must never be moved by prefix inference.
pub(super) const PROVEN_NANO_SKILL_OWNERS: &[&str] = &[
    "damage_aku",
    "damage_billy",
    "damage_bubbles",
    "damage_deedee",
    "damage_demongo",
    "damage_humongosaur",
    "damage_numbuh1",
    "damage_samuraijack",
    "dot_mojojojo",
    "dot_numbuh4",
    "dot_root",
    "freedom_billy",
    "freedom_coco",
    "freedom_humongosaur",
    "freedom_root",
    "heal_root",
    "jump_bubbles",
    "jump_mandark",
    "jump_root",
    "jump_samuraijack",
    "jump_utonium",
    "jump_wilt",
    "minimap_edd",
    "minimap_root",
    "minimap_vilgax",
    "nano_freedom_coco",
    "nano_protectionbattery_coco",
    "phoenix_demongo",
    "phoenix_numbuh5",
    "phoenix_root",
    "protectionbattery_coco",
    "protectionbattery_root",
    "protectioninfection_root",
    "recall_root",
    "retrorocket_dexter",
    "retrorocket_root",
    "rewardfusion_root",
    "rewardmoney_root",
    "run_hex",
    "run_mandy",
    "run_root",
    "sleep_hex",
    "sleep_megas",
    "sleep_root",
    "sleep_swampfire",
    "snare_bloo",
    "snare_bubbles",
    "snare_humongosaur",
    "snare_juniper",
    "snare_root",
    "snare_wilt",
    "stealth_root",
    "stun_bloo",
    "stun_blossom",
    "stun_coco",
    "stun_mandark",
    "stun_root",
    "vampire_fourarms",
    "vampire_juniper",
    "vampire_numbuhfive",
];

/// Recovery-only Nano abilities proven by the Nano.resourceFile audit.
pub(super) const RECOVERY_NANO_SKILLS: &[(&str, &str, &str)] = &[
    ("heal_panini_powderedflarts", "heal", "panini"),
    ("retrorocket_panini_coptermode", "retrorocket", "panini"),
    ("rewardfusion_coop_bottomlesspit", "rewardfusion", "coop"),
    ("rewardmoney_coop_cheatcode", "rewardmoney", "coop"),
    ("stun_coop_thejammer", "stun", "coop"),
    ("stun_panini_motherlyinstinct", "stun", "panini"),
];

/// Proven Nano speaker name prefixes. The first item is the source spelling and
/// the second item is the stable content ID shared with `characters/nanos`.
pub(super) const NANO_IDENTITY_ALIASES: &[(&str, &str)] = &[
    ("jackolantern", "jackolantern"),
    ("johnnybravo", "johnnybravo"),
    ("profutonium", "utonium"),
    ("samuraijack", "samuraijack"),
    ("humongosaur", "humongousaur"),
    ("numbuhthree", "numbuhthree"),
    ("numbuhfive", "numbuhfive"),
    ("numbuhfour", "numbuhfour"),
    ("numbuhone", "numbuhone"),
    ("numbuhtwo", "numbuhtwo"),
    ("belladonnanan", "belladonna"),
    ("juniperlee", "juniper_lee"),
    ("mojojojo", "mojojo"),
    ("mojo", "mojojo"),
    ("belladonna", "belladonna"),
    ("buttercup", "buttercup"),
    ("fourarms", "4arms"),
    ("swampfire", "swampfire"),
    ("demongo", "demongo"),
    ("eduardo", "eduardo"),
    ("jbravo", "johnnybravo"),
    ("juniper", "juniper_lee"),
    ("numthree", "numbuhthree"),
    ("numfive", "numbuhfive"),
    ("numfour", "numbuhfour"),
    ("numone", "numbuhone"),
    ("numtwo", "numbuhtwo"),
    ("humongo", "humongousaur"),
    ("btrcup", "buttercup"),
    ("sjack", "samuraijack"),
    ("deedee", "deedee"),
    ("courage", "courage"),
    ("blossom", "blossom"),
    ("bubbles", "bubbles"),
    ("mandark", "mandark"),
    ("vilgax", "vilgax"),
    ("wilt", "wilt"),
    ("dexter", "dexter"),
    ("cheese", "cheese"),
    ("panini", "panini"),
    ("runty", "runty"),
    ("billy", "billy"),
    ("megas", "megas"),
    ("mandy", "mandy"),
    ("coco", "coco"),
    ("coop", "coop"),
    ("grim", "grim"),
    ("finn", "finn"),
    ("bloo", "bloo"),
    ("aku", "aku"),
    ("utonium", "utonium"),
    ("edd", "edd"),
    ("eddy", "eddy"),
    ("ed", "ed"),
    ("mac", "mac"),
    ("him", "him"),
    ("hex", "hex"),
    ("ben", "ben"),
];
