
pub(super) const ADDITIVE_TRANSPARENT_SCRIPT: &str = concat!(
        "Shader \"normal_blendSrcalphaOne_zwriteOff\" {\n",
        "Properties {\n",
        "\t_Color (\"Main Color\", Color) = (1,1,1,1)\n",
        "\t_SpecColor (\"Spec Color\", Color) = (1,1,1,1)\n",
        "\t_AmbColor (\"Ambient Color\", Color) = (1,1,1,1)\n",
        "\t_Emission (\"Emmisive Color\", Color) = (0,0,0,0)\n",
        "\t_Shininess (\"Shininess\", Range (0.01, 1)) = 0.7\n",
        "\t_MainTex (\"Base (RGB)\", 2D) = \"white\" {}\n",
        "}\n",
        "\n",
        "Category {\n",
        "\tTags {\"Queue\"=\"Transparent+10\"}\n",
        "\n",
        "\tBlend SrcAlpha One \n",
        "\tColorMask RGB\n",
        "\tZWrite Off\n",
        "\t\n",
        "\n",
        "\tSubShader {\n",
        "\t\tPass {\n",
        "\t\t\tMaterial {\n",
        "\t\t\t\tDiffuse [_Color]\n",
        "\t\t\t\tAmbient [_AmbColor]\n",
        "\t\t\t\tShininess [_Shininess]\n",
        "\t\t\t\t//\tSpecular [_SpecColor]\n",
        "\t\t\t\tEmission [_Emission]\n",
        "\t\t\t} \n",
        "\t\t\tLighting On\n",
        "\t\t\tSetTexture [_MainTex] {\n",
        "\t\t\t\tCombine texture * primary DOUBLE , texture\n",
        "\t\t\t} \n",
        "\t\t}\n",
        "\t}\n",
        "}\n",
        "}"
    );

pub(super) const ADDITIVE_TRANSPARENT_CULL_OFF_SCRIPT: &str = concat!(
        "Shader \"normal_blendSrcalphaOne_zwriteOff_cullOff\" {\n",
        "Properties {\n",
        "\t_Color (\"Main Color\", Color) = (1,1,1,1)\n",
        "\t_SpecColor (\"Spec Color\", Color) = (1,1,1,1)\n",
        "\t_AmbColor (\"Ambient Color\", Color) = (1,1,1,1)\n",
        "\t_Emission (\"Emmisive Color\", Color) = (0,0,0,0)\n",
        "\t_Shininess (\"Shininess\", Range (0.01, 1)) = 0.7\n",
        "\t_MainTex (\"Base (RGB)\", 2D) = \"white\" {}\n",
        "}\n",
        "\n",
        "Category {\n",
        "\tTags {\"Queue\"=\"Transparent+10\"}\n",
        "\tBlend SrcAlpha One \n",
        "\tColorMask RGB\n",
        "\tZWrite Off\n",
        "\tCull Off\n",
        "\t\n",
        "\n",
        "\tSubShader {\n",
        "\t\tPass {\n",
        "\t\t\tMaterial {\n",
        "\t\t\t\tDiffuse [_Color]\n",
        "\t\t\t\tAmbient [_AmbColor]\n",
        "\t\t\t\tShininess [_Shininess]\n",
        "\t\t\t\t//\tSpecular [_SpecColor]\n",
        "\t\t\t\tEmission [_Emission]\n",
        "\t\t\t} \n",
        "\t\t\tLighting On\n",
        "\t\t\tSetTexture [_MainTex] {\n",
        "\t\t\t\tCombine texture * primary DOUBLE , texture\n",
        "\t\t\t} \n",
        "\t\t}\n",
        "\t}\n",
        "}\n",
        "}"
    );
